# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Content.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rContent.proto\"\x07\n\x05\x45mpty\"\x82\x02\n\rContentScheme\x12\x12\n\ncontent_id\x18\x01 \x01(\t\x12\x0c\n\x04spam\x18\x02 \x01(\x02\x12.\n\x08\x65motions\x18\x03 \x03(\x0b\x32\x1c.ContentScheme.EmotionsEntry\x12\x38\n\rpersonalities\x18\x04 \x03(\x0b\x32!.ContentScheme.PersonalitiesEntry\x1a/\n\rEmotionsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\x1a\x34\n\x12PersonalitiesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\"&\n\x08\x43ontents\x12\x0b\n\x03ids\x18\x01 \x03(\t\x12\r\n\x05texts\x18\x02 \x03(\t\"\x1b\n\nContentIDs\x12\r\n\x05items\x18\x01 \x03(\t\"\x16\n\x06Search\x12\x0c\n\x04text\x18\x01 \x01(\t\"\x1a\n\tSentences\x12\r\n\x05items\x18\x01 \x03(\t\"\x1a\n\tSpamProbs\x12\r\n\x05items\x18\x01 \x03(\x02\"\x16\n\x06Status\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x32\xdb\x01\n\x07\x43ontent\x12*\n\x0bPersonalize\x12\t.Contents\x1a\x0e.ContentScheme\"\x00\x12&\n\x0eInsertContents\x12\t.Contents\x1a\x07.Status\"\x00\x12\"\n\x08Rollback\x12\x0b.ContentIDs\x1a\x07.Status\"\x00\x12(\n\x0eSemanticSearch\x12\x07.Search\x1a\x0b.ContentIDs\"\x00\x12.\n\x12\x43\x61lculateSpamProbs\x12\n.Sentences\x1a\n.SpamProbs\"\x00\x42\x37Z5github.com/wholesome-ghoul/persona-prototype-6/protosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Content_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z5github.com/wholesome-ghoul/persona-prototype-6/protos'
  _globals['_CONTENTSCHEME_EMOTIONSENTRY']._options = None
  _globals['_CONTENTSCHEME_EMOTIONSENTRY']._serialized_options = b'8\001'
  _globals['_CONTENTSCHEME_PERSONALITIESENTRY']._options = None
  _globals['_CONTENTSCHEME_PERSONALITIESENTRY']._serialized_options = b'8\001'
  _globals['_EMPTY']._serialized_start=17
  _globals['_EMPTY']._serialized_end=24
  _globals['_CONTENTSCHEME']._serialized_start=27
  _globals['_CONTENTSCHEME']._serialized_end=285
  _globals['_CONTENTSCHEME_EMOTIONSENTRY']._serialized_start=184
  _globals['_CONTENTSCHEME_EMOTIONSENTRY']._serialized_end=231
  _globals['_CONTENTSCHEME_PERSONALITIESENTRY']._serialized_start=233
  _globals['_CONTENTSCHEME_PERSONALITIESENTRY']._serialized_end=285
  _globals['_CONTENTS']._serialized_start=287
  _globals['_CONTENTS']._serialized_end=325
  _globals['_CONTENTIDS']._serialized_start=327
  _globals['_CONTENTIDS']._serialized_end=354
  _globals['_SEARCH']._serialized_start=356
  _globals['_SEARCH']._serialized_end=378
  _globals['_SENTENCES']._serialized_start=380
  _globals['_SENTENCES']._serialized_end=406
  _globals['_SPAMPROBS']._serialized_start=408
  _globals['_SPAMPROBS']._serialized_end=434
  _globals['_STATUS']._serialized_start=436
  _globals['_STATUS']._serialized_end=458
  _globals['_CONTENT']._serialized_start=461
  _globals['_CONTENT']._serialized_end=680
# @@protoc_insertion_point(module_scope)
